
baseurl: ''

lang: en

timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Fei Li's Website

tagline: data science and programming blogs 

description: >-
  Fei Li's data science and programming blogs.



url: 'https://lifei.tech'

image: '/assets/imgs/website-post.jpg'

github:
  username: lifeitech

# twitter:
#   username:

social:
  name: Fei Li
  email: fei.li.best@gmail.com
  links:
    - https://www.lifei.tech
    - https://github.com/lifeitech     
    - https://www.linkedin.com/in/lifeipro

google_site_verification: google_meta_tag_verification

# ↑ --------------------------


google_analytics:
  id: 'G-QV43D2GXK2'
  pv:
    proxy_endpoint:
    cache_path: 


theme_mode: light # [light|dark]

avatar: '/assets/imgs/avatar.jpg'

toc: true

disqus:
  comments: true
  shortname: 'www-lifei-tech'

paginate: 6

plugins:
  - jekyll
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-scholar


# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
